version: '3'
services:
  db:
    image: postgres:12.2
    container_name: ${APP_NAME}-postgres
    restart: always
    environment:
      POSTGRES_DB: test_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5431:5432"
    networks:
      testing_net:
        ipv4_address: 172.10.1.5

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: ${APP_NAME}-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    networks:
      testing_net:
        ipv4_address: 172.10.1.4

    links:
      - "db:pgsql-server"

  redis:
    image: "redis:alpine"
    container_name: ${APP_NAME}-redis
    ports:
      - "6372:6379"
    networks:
      testing_net:
        ipv4_address: 172.10.1.2
  app:
    build:
      context: .
      dockerfile: .docker/apache2/Dockerfile
      args:
        uid: ${UID}
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - "8021:80"
      - "465:443"
    networks:
      testing_net:
        ipv4_address: 172.10.1.7
    volumes:
      - .:/var/www/html
    depends_on:
      - db
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16

